# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spModelAll <- function(xvec, y1, y2, delta1, delta2, x1, x2, x3, wts, m1pred, m2pred, m3pred, penalty, penaltyMat1, penaltyMat2, penaltyMat3, kappa1, kappa2, kappa3) {
    .Call('_FreqIDSpline_spModelAll', PACKAGE = 'FreqIDSpline', xvec, y1, y2, delta1, delta2, x1, x2, x3, wts, m1pred, m2pred, m3pred, penalty, penaltyMat1, penaltyMat2, penaltyMat3, kappa1, kappa2, kappa3)
}

sandwichEstCheese <- function(xvec, y1, y2, delta1, delta2, x1, x2, x3, wts, m1pred, m2pred, m3pred) {
    .Call('_FreqIDSpline_sandwichEstCheese', PACKAGE = 'FreqIDSpline', xvec, y1, y2, delta1, delta2, x1, x2, x3, wts, m1pred, m2pred, m3pred)
}

logLikNoPenal <- function(xvec, y1, y2, delta1, delta2, x1, x2, x3, wts, m1pred, m2pred, m3pred) {
    .Call('_FreqIDSpline_logLikNoPenal', PACKAGE = 'FreqIDSpline', xvec, y1, y2, delta1, delta2, x1, x2, x3, wts, m1pred, m2pred, m3pred)
}

logLikPenal <- function(xvec, y1, y2, delta1, delta2, x1, x2, x3, wts, m1pred, m2pred, m3pred, m1deriv2pred, m2deriv2pred, m3deriv2pred, kappa1, kappa2, kappa3) {
    .Call('_FreqIDSpline_logLikPenal', PACKAGE = 'FreqIDSpline', xvec, y1, y2, delta1, delta2, x1, x2, x3, wts, m1pred, m2pred, m3pred, m1deriv2pred, m2deriv2pred, m3deriv2pred, kappa1, kappa2, kappa3)
}

spModelUniv <- function(xvec, nObs, nCov, nKnots, y, delta, x1, wts, bpred) {
    .Call('_FreqIDSpline_spModelUniv', PACKAGE = 'FreqIDSpline', xvec, nObs, nCov, nKnots, y, delta, x1, wts, bpred)
}

spModelUnivFixedBeta <- function(xvec, beta, nObs, nCov, nKnots, y, delta, x1, wts, bpred) {
    .Call('_FreqIDSpline_spModelUnivFixedBeta', PACKAGE = 'FreqIDSpline', xvec, beta, nObs, nCov, nKnots, y, delta, x1, wts, bpred)
}

spModelExample <- function(params, xInterp, yInterp, xVals, nObs) {
    .Call('_FreqIDSpline_spModelExample', PACKAGE = 'FreqIDSpline', params, xInterp, yInterp, xVals, nObs)
}

